myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include #引入include方法
from utils.upload import upload_file


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('',include('tliublog.urls')),
    path('uploads/', upload_file, name='uploads')
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

myblog/tliublog/urls.py
from django.urls import path
from . import views

app_name = "tliublog"

urlpatterns = [
    path('',views.Index_view,name='index'),
    path('category/<int:category_id>/',views.category_list,name="category_list"),
    path('article/<int:article_id>/',views.article_detail,name="article_detail"),
    path('search/',views.search,name='search'),
    path('archives/<int:year>/<int:month>',views.archives,name="archives")
]

myblog/users/urls.py
from email import header
from pathlib import Path
from django.urls import path
from . import views

app_name = 'users'

urlpatterns=[
    path('login/',views.login_view,name='login'),
    path('register/',views.register,name = 'register'),
    path('active/<active_code>',views.active_user,name = 'active_user'),
    path('forget_pwd/',views.forget_pwd,name='forget_pwd'),
    path('forget_pwd_url/<active_code>',views.forget_pwd_url,name='forget_pwd_url'),
    path('user_profile/',views.user_profile,name='user_profile'),
    path('logout/',views.logout_view,name='logout'),
    path('edit_user/',views.edit_user,name='edit_user'),
    ]

myblog/tliublog/models.py
from distutils.command.upload import upload
from email.headerregistry import Address
from email.policy import default
from http.client import UNSUPPORTED_MEDIA_TYPE
from pyexpat import model
from re import I, M
from tabnanny import verbose
from this import d
from unittest.util import _MAX_LENGTH
from django.db import models
from django.forms import DateTimeField
from django.test import tag
from django.contrib.auth.models import User
from django.utils.functional import cached_property #缓存装饰器
from django.template.loader import render_to_string # 渲染模板


# Create your models here.
class Category(models.Model):
    '''博客的分类模型'''
    name = models.CharField(max_length=50,verbose_name='分类名称')
    desc = models.TextField(max_length=200,blank=True,default='', verbose_name='分类描述')
    add_date = models.DateTimeField(auto_now_add=True,verbose_name='添加时间')
    pub_date = models.DateTimeField(auto_now_add=True,verbose_name='修改时间')
    

    class Meta:
        verbose_name = "博客分类"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name
 

class Tag(models.Model):
    '''文章标签'''
    name = models.CharField(max_length=50,verbose_name="文章标签")
    add_date = models.DateTimeField(auto_now_add=True,verbose_name='添加时间')
    pub_date = models.DateTimeField(auto_now_add=True,verbose_name='修改时间')

    class Meta:
        verbose_name = "文章标签"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name



class Article(models.Model):
    '''文章'''
    title = models.CharField(max_length=50,verbose_name='文章标题')
    desc = models.TextField(max_length=200,verbose_name="文章描述")
    category = models.ForeignKey(Category,on_delete=models.CASCADE,verbose_name="文章分类")
    content = models.TextField(verbose_name="文章内容")
    tags = models.ForeignKey(Tag,on_delete=models.CASCADE,verbose_name="文章标签")
    author = models.ForeignKey(User, verbose_name="作者", on_delete=models.CASCADE)
    is_hot = models.BooleanField(default=False,verbose_name="是否热门")  # 手动热门推荐
    pageview = models.IntegerField(default=0,verbose_name="浏览量")
    add_date = models.DateTimeField(auto_now_add=True,verbose_name='添加时间')
    pub_date = models.DateTimeField(auto_now_add=True,verbose_name='修改时间')
    

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name
        ordering = ['-pub_date']

    def __str__(self):
        return self.title

class Sidebar(models.Model):
    # 侧边栏的模型数据

    STATUS = (
        (1, '隐藏'),
        (2, '展示')
    )

    DISPLAY_TYPE = (
        (1, '搜索'),
        (2, '最新文章'),
        (3, '最热文章'),
        (4, '最近评论'),
        (5, '文章归档'),
        (6, 'HTML')
    )
    title = models.CharField(max_length=50, verbose_name="模块名称")
    display_type = models.PositiveBigIntegerField(default=1,choices=DISPLAY_TYPE,verbose_name="展示类型")
    content = models.CharField(max_length=500,blank=True,default='',verbose_name="内容",help_text="如果设置的不是HTML类型,可为空")
    sort = models.PositiveIntegerField(default=1,verbose_name="排序",help_text="序号越大越靠前")
    status = models.PositiveIntegerField(default=2,choices=STATUS,verbose_name="状态")
    add_date = models.DateTimeField(auto_now_add=True,verbose_name="发布时间")


    class Meta:
        verbose_name = "侧边栏"
        verbose_name_plural = verbose_name
        ordering = ['-sort']
    def __str__(self):
        return self.title

    @classmethod   # 类方法装饰器，这个就变成了这个类的一个方法，可以调用
    def get_sidebar(cls):
        return cls.objects.filter(status=2)  # 允许展示的模块

    @property   #成为一个类属性，调用的时候不需要后面（），是只读的，用户没办法修改
    def get_content(self):
        if self.display_type == 1:
            context = {}
            return render_to_string('tliublog/sidebar/search.html', context)
        elif self.display_type == 2:
            context = {}
            return render_to_string('tliublog/sidebar/new_article.html',context)
        elif self.display_type == 3:
            context = {}
            return render_to_string('tliublog/sidebar/hot_article.html', context)
        elif self.display_type == 4:  
            context = {}
            return render_to_string('tliublog/sidebar/comment.html', context)
        elif self.display_type == 5:   # 文章归档
            context = {}
            return render_to_string('tliublog/sidebar/archives.html', context)
        elif self.display_type == 6:   # 自定义侧边栏
           
            return self.content   # 在侧边栏直接使用这里的html，模板中必须使用safe过滤器去渲染HTML


    
    
    

myblog/tliublog/views.py
from unicodedata import category
from urllib.request import Request
from django.shortcuts import render,get_object_or_404
from .models import Category,Article
from django.db.models import Q,F
from django.core.paginator import Paginator

# Create your views here.


def Index_view(request):

    # category_list = Category.objects.all()
    article_list = Article.objects.all()
    print(article_list)
    paginator = Paginator(article_list,2) #第二个参数2代表每页显示几个
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj':page_obj}
    return render(request,"tliublog/index.html",context)


def category_list(request,category_id):
    # 获取分类下的所有文章
    category = get_object_or_404(Category,id=category_id)
    article_list = category.article_set.all()
    paginator = Paginator(article_list,2) #第二个参数2代表每页显示几个
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'category':category,'page_obj':page_obj}
    
    return render(request,'tliublog/list.html',context)


def article_detail(request,article_id):
    # 文章详情页
    article = get_object_or_404(Article,id = article_id)
    
    # 通过文章id来实现上下篇
    prev_article = Article.objects.filter(id__lt=article_id).last() #上一篇
    next_article = Article.objects.filter(id__gt=article_id).first() #下一篇
    Article.objects.filter(id=article_id).update(pageview = F('pageview')+1)
    # 通过发布日期来实现上下篇
    # date_prev_article = Article.objects.filter(add_date__lt=article.add_date).last() #上一篇
    # date_next_article = Article.objects.filter(add_date__gt=article.add_date).first() #下一篇
    # print(date_prev_article)
    # print(date_next_article)

    context = {"article":article, "prev_article":prev_article,"next_article":next_article}

    return render(request, "tliublog/detail.html",context)


def search(request):

    keyword = request.GET.get('keyword')
    if not keyword:
        article_list = Article.objects.all()
    else:
        article_list = Article.objects.filter(Q(title__icontains=keyword) | Q(desc__icontains=keyword) | Q(content__icontains=keyword))
    paginator = Paginator(article_list,2) #第二个参数2代表每页显示几个
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context  = {'page_obj':page_obj}
    return render(request,'tliublog/index.html',context)



def archives(request,year,month):

    article_list = Article.objects.filter(add_date__year=year,add_date__month=month)
    paginator = Paginator(article_list,2) #第二个参数2代表每页显示几个
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj':page_obj,'year':year,'month':month}
    return render(request,'tliublog/archives_list.html',context)

myblog/tliublog/templates/tliublog/archives_list.html
{% extends 'tliublog/base.html' %}

{% block title %}
{{ year }}{{month}}的归档
{% endblock  %}
{% block archives %}
    <!-- 显示当前分类模块 -->
    <div class="box">
        每月归档：{{ year }}年{{ month }}月
        <div class="tags has-addons is-pulled-right">
          <span class="tag">共</span>
          <span class="tag is-primary">{{ article_list.count }} 篇</span>
        </div>
    </div>
    <!-- 显示当前分类模块 end-->
{% endblock  %}

myblog/tliublog/templates/tliublog/base.html
<!DOCTYPE html>
{% load static category  %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'users/bulma.css' %}">
    <title>{% block title %}时光的小河流{% endblock  %}</title>
</head>
<body>
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="https://bulma.io">
        <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
      </a>
  
      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
  
    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        {% block navbar-start %}
        <a class="navbar-item" href="/">
          首页
        </a>
        {% get_category_list as category_list %}
        {% for category in category_list %}
        <a class="navbar-item" href="{% url 'tliublog:category_list' category.id %}">
          {{ category.name }}
        </a>
        {% endfor %}
  
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            More
          </a>
  
          <div class="navbar-dropdown">
            <a class="navbar-item">
              About
            </a>
            <a class="navbar-item">
              Jobs
            </a>
            <a class="navbar-item">
              Contact
            </a>
            <hr class="navbar-divider">
            <a class="navbar-item">
              Report an issue
            </a>
          </div>
        </div>
        {% endblock  %}
      </div>
  
      <div class="navbar-end">
        {% block navbar-end %}
        <div class="navbar-item">
          {% if user.is_authenticated %}
          <div class="buttons">
              <a href="{% url 'users:user_profile' %}" class="button is-is-outlined is-light">{{ request.user.username }}</a>
              <a href="{% url 'users:logout' %}" class="button is-primary is-light">退出</a>
          </div>
          {% else %}
          <div class="buttons">
            <a class="button is-primary" href="{% url 'users:register' %}" target="_blank">
              <strong>注册</strong>
            </a>
            <a class="button is-light" href="{% url 'users:login' %}" target="_blank">
              登录
            </a>
          </div>
          {% endif %}
        </div>
        {% endblock  %}
      </div>
    </div>
  </nav>
  <section class="container">
    <div class="container">
      <div class="columns">
        <div class="column is-8">
          {% block section %}
          {% block archives %}{% endblock  %}
          {% if page_obj %}
					  {% for article in page_obj %}
          
            <div class="box">
              <h1 class= "is-size-5">
                <a href="{% url 'tliublog:article_detail' article.id %}">{{article.title}}</a>
              </h1>
              <div class="is-size-7 has-text-has-text-grey-light pt-1 pb-1">
                <span class="mr-3">作者：{{article.author}}</span><span>发布日期：{{article.add_date}}</span>
              </div>
              <p>{{ article.desc|truncatechars:50 }}</p>
            </div>
            {% endfor %}
          {% else %}
          <div class="box">
            <p class="has-text-danger">没有匹配的文章！</p>
          </div>
          {% endif %}
          {% if page_obj %}
						<nav class="pagination is-centered" role="navigation" aria-label="pagination">
						{% if page_obj.has_previous %}
							<a class="pagination-previous" href="?page={{ page_obj.previous_page_number }}">Previous</a>
						{% endif %}
						{% if page_obj.has_next %}
						<a class="pagination-next" href="?page={{ page_obj.next_page_number }}">Next page</a>
						{% endif %}
						<ul class="pagination-list">
						{% if page_obj.has_previous %}
							<li><a class="pagination-link" aria-label="Goto page 45" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
						{% endif %}
							<li><a class="pagination-link is-current" aria-label="Page {{ page_obj.number }}" aria-current="page" href='?page={{ page_obj.number }}'>{{ page_obj.number }}</a></li>
						{% if page_obj.has_next %}
							<li><a class="pagination-link" href="?page={{ page_obj.next_page_number }}" aria-label="Goto page {{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
						{% endif %}
						</ul>
						</nav>
						{% endif %} 
          {% endblock  %}
        </div>
        <div class="column is-4">
          {% block right %}
          {% get_sidebar_list as sidebar_list %}
          {% for sidebar in sidebar_list %}
          <div class="box">
            <h1 class="is-size-5 title">{{ sidebar.title }}</h1>
            <p>{{sidebar.get_content|safe}}</p>
          </div>
          {% endfor %}
          {% endblock  %}
        </div>
      </div>
    </div>
  </section>
  {% block footer %}
    <footer class="footer container mt-6">
      <div class="container has-text-centered">
        博客底部
      </div>
    </footer>
  {% endblock  %}
</body>
</html>

myblog/tliublog/templates/tliublog/detail.html
{% extends 'tliublog/base.html' %}
{% block section %}
<div class="box">
    <h1 class="title is-size-5 has-text-weight-bold">
        <a>{{ article.title }}</a>
    </h1>
    <div class = "is-size-7 has-text-grey-light pt-1 pb-1">
        <span class="mr-3">作者：{{ article.author }}</span><span>发布日期：{{ article.add_date}}</span><span>浏览量：{{article.pageview}}</span>
    </div>
    <div class="content">
        {{article.content|safe}}
    </div>
</div>

<div class="box">
<div class="level">
    <div class="level-left">
        {% if prev_article %}
        <span>上一页: </span><a href="{% url 'tliublog:article_detail' prev_article.id %}" class="level-item">{{ prev_article.title }}</a>
        {% else %}
        <span class="has-text-danger-dark is-size-7">首页</span>
        {% endif %}
    </div>
    <div class="level-right">
        {% if next_article %}
        <span>下一页: </span><a href="{% url 'tliublog:article_detail' next_article.id %}" class="level-item">{{ next_article.title }}</a>
        {% else %}
        <span class="has-text-danger-dark is-size-7">尾页</span>
        {% endif %}
    </div>
</div>
</div>
{% endblock %}

myblog/tliublog/templates/tliublog/index.html
{% extends 'tliublog/base.html' %}

myblog/tliublog/templates/tliublog/list.html
{% extends 'tliublog/base.html' %}